export const SEARCH_MOVIES_BY_TITLE = "SEARCH_MOVIES_BY_TITLE";
export const LOADING = "LOADING";
export const DISCOVER_MOVIES = "DISCOVER_MOVIES";
export const SEARCH_MOVIE_BY_ID = "SEARCH_MOVIE_BY_ID";
